# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: etranchi <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/04/10 16:15:30 by etranchi          #+#    #+#              #
#    Updated: 2017/04/10 16:18:50 by etranchi         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC=gcc
CFFLAGS= -Wall -Werror -Wextra
EXEC=ft_display_file

all:
	$(CC) -o $(EXEC) $(EXEC).c

clean :
	rm -rf *.o

fclean : 
	rm -rf *.o
	rm -rf $(EXEC)
